# Generated by Django 3.0.5 on 2020-05-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crypto2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=30)),
                ('tx_date', models.DateTimeField(verbose_name='TX Date')),
                ('tx_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
