# Generated by Django 3.0.5 on 2020-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto2', '0002_auto_20200523_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=120, verbose_name='tx_id')),
                ('tx_date', models.DateTimeField(verbose_name='tx_date')),
                ('tx_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tx_amount')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
