# Generated by Django 3.0.5 on 2020-05-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto2', '0005_crypto_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crypto_load',
        ),
    ]
